name: genclik_spor
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^28.2.12
  syncfusion_flutter_pdf: ^28.2.12
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/images/ 
    - assets/fonts/
    - assets/mocks/athlete.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
